// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDa2lPwtNIGjTs6SeZqTA9U7BAorzGOJrA',
    appId: '1:563489734928:web:acbbd38ce8edb50bede595',
    messagingSenderId: '563489734928',
    projectId: 'mobileapp-tutorial',
    authDomain: 'mobileapp-tutorial.firebaseapp.com',
    storageBucket: 'mobileapp-tutorial.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtWgMR9uLRPU2fPQ9o8xQ76YWBJRkWq9U',
    appId: '1:563489734928:android:4dee8553904ee831ede595',
    messagingSenderId: '563489734928',
    projectId: 'mobileapp-tutorial',
    storageBucket: 'mobileapp-tutorial.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjMfjNZThWqtgAPI52hHoXCWJdtcfeeO4',
    appId: '1:563489734928:ios:48959d76db5ac51dede595',
    messagingSenderId: '563489734928',
    projectId: 'mobileapp-tutorial',
    storageBucket: 'mobileapp-tutorial.firebasestorage.app',
    iosBundleId: 'com.example.authenticationTutorial',
  );

}